### ISSUE TITLE
Improve password hashing

### ISSUE THREAD

**Issue by mtornwall** [StarcounterPrefabs/Simplified#28]
Storing passwords as a salted SHA256 hash is not safe now that GPU cracking is commonplace.

Modern password storage should use a memory-hard key derivation function (such as [scrypt](https://en.wikipedia.org/wiki/scrypt) or the more recent [Argon2](https://en.wikipedia.org/wiki/Argon2)) in order to thwart GPU attacks.

**Comment by miyconst** [comment]
And the C# implementation - [Replicon.Cryptography.SCrypt](https://github.com/replicon/Replicon.Cryptography.SCrypt).

**Comment by miyconst** [comment]
This issue could be done together with [Replace client side hashing with client side encryption](https://github.com/StarcounterPrefabs/SignIn/issues/34).

**Comment by miyconst** [comment]
Implemented by me and checked by @warpech. Closing the issue.
