### ISSUE TITLE
Merge develop branch into master

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Simplified#34]
I think it was agree to merge the develop branch into master, since it is backwards compatible, and it Simplified should not be treated as an app, rather as a piece of Starcounter.

@warpech can you confirm?

**Comment by warpech** [comment]
Yes, I agree. Can you please do the merge?

**Comment by miyconst** [comment]
Will do so.

**Comment by andwah** [comment]
When this is done i will start making new versions of SignIn, UserAdmin and Registration

**Comment by miyconst** [comment]
We have to modify our build script to enable unsafe code for Simplified.

This line of code causes a build error.

```
 C:\TeamCity\BuildAgent\work\sc-pnext-daily-windows-2526\Level1\bin\Release>"c:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\TeamCity\BuildAgent\work\sc-pnext-daily-windows-2526/Simplified/Simplified.sln" /p:ReferencePath="C:\TeamCity\BuildAgent\work\sc-pnext-daily-windows-2526\Level1\Bin\Release;C:\TeamCity\BuildAgent\work\sc-pnext-daily-windows-2526\Level1\Bin\Release/EditionLibraries" /p:Configuration=Release /maxcpucount /verbosity:minimal 
```

```
lib\Scrypt\ScryptEncoder.cs(189,36): error CS0227: Unsafe code may only appear if compiling with /unsafe [C:\TeamCity\BuildAgent\work\sc-pnext-daily-windows-2526\Simplified\Simplified.csproj]
```

Although it is enabled in the `Simplified.csproj` file, it still fails on the build server.

```
<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
```

cc @alemoi, @ubbeK

**Comment by miyconst** [comment]
Done. Should be available in the next nightlies. Had to remove the `[Obsolete]` attribute though. https://github.com/StarcounterPrefabs/Simplified/issues/35

**Comment by andwah** [comment]
Thanks.. @miyconst   tomorrow i will build new versions of  SignIn, UserAdmin and Registration
