### ISSUE TITLE
Adapt Simplifed to upcoming 2.4 changes

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/Simplified#36]
Background here: https://github.com/Starcounter/Starcounter/issues/3946#issuecomment-261180485

Should be assigned to me (I seem not to have that privilege).

**Comment by per-samuelsson** [comment]
> Should be assigned to me (I seem not to have that privilege).

And clearly, I can't push either then. 😸 @miyconst, any chance you could give me those permissions? I promise I won't mess with the master branches.

If you think it's better I fork and send a PR, that's fine I guess. Just that I don't want anything pulled into any master branch anyway. ❗️❓

**Comment by per-samuelsson** [comment]
> And clearly, I can't push either then. 😸 @miyconst, any chance you could give me those permissions? I promise I won't mess with the master branches.

Hah! I just lurked around and noticed that @warpech already had given me an invitation to `StarcounterPrefabs` a really long time ago. Just joined, and now I'm on track again. 👍

**Comment by per-samuelsson** [comment]
When this is merged in main branch, we must update this https://github.com/StarcounterPrefabs/Simplified#distributed-with-starcounter and this https://github.com/StarcounterPrefabs/Simplified#building-your-own.

**Comment by per-samuelsson** [comment]
Is it documented somewhere how Simplified (and SocietyObjects) relate to different versions of Starcounter?

cc @miyconst @warpech

**Comment by miyconst** [comment]
>Is it documented somewhere how Simplified (and SocietyObjects) relate to different versions of Starcounter?

Sorry, I don't get the question. As of now the `Simplified` library was shipped with Starcounter. So, it was no how related to different versions of Starcounter, it was a part of it.

**Comment by per-samuelsson** [comment]
> Sorry, I don't get the question. As of now the Simplified library was shipped with Starcounter. So, it was no how related to different versions of Starcounter, it was a part of it.

Sorry, I was probably not clear enough. I've made some changes in *how* it's bundled with Starcounter, but we have decided that it will be still. The changing thing is that it will need to be explicitly referenced from projects that want to use it (just like normal references).

But my question was how Simplified relate to *different versions of Starcounter*. The thing I'm doing right now, which this issue is about, is that I'm changing Simplified so that (in this branch) it is compatible with the recent changes in **2.3** ("pnext") of Starcounter. If I would merge those into the main branch of Simplified, Simplified would no longer be compatible with Starcounter 2.2.

I can set up the build-server so that when building Starcounter 2.3, it build a certain branch of Simplified. And when building 2.2, it can use another branch. My question was basically if there was a recommended pattern for that, i.e. that we use "develop" for "latest" Starcounter, and that we have some other Simplified branch for earlier versions (i.e. 2.2, 2.1).

**Comment by miyconst** [comment]
No such things for Simplified as I know. Maybe @warpech can add some more.

I wander, which changes broke the compatibility with Starcounter 2.2?

**Comment by per-samuelsson** [comment]
> I wander, which changes broke the compatibility with Starcounter 2.2?

No code changes (yet). Just changes relating to how the Simplified project must be built and bundled with Starcounter. We are just discussing breaking code changes that we have plan for. The probably will end up in some 2.4 version.

Thanks for the feedback @miyconst. I have a clearer picture now. I'll consider what options there are and I'll update here once this whole thing get merged.

**Comment by miyconst** [comment]
Still, I would like to see those new features in Simplified, which do not work in Starcounter 2.2, even if it is not yet there.

**Comment by per-samuelsson** [comment]
Note to self: Need to adapt to https://github.com/Starcounter/Starcounter/issues/3980 too.

**Comment by per-samuelsson** [comment]
> Note to self: Need to adapt to Starcounter/Starcounter#3980 too.

Done.

**Comment by per-samuelsson** [comment]
Merged: https://github.com/StarcounterPrefabs/Simplified/commit/49aac67c5f2299f51b30de58ee97e9b308fd0b51
